import { ChangeDetectionStrategy, Component, computed, inject, OnDestroy, OnInit, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { RealtimeChannel } from '@supabase/supabase-js';
import { PageActionsService } from '../../../core/services/page-actions.service';
import { AuthStore } from '../../auth/store/auth.store';
import { MatchActionSheet } from '../components/match-action-sheet';
import { MatchCard } from '../components/match-card';
import { BeachMatch } from '../models/match.model';
import { MatchesService } from '../services/matches.service';
import { MatchesStore } from '../store/matches.store';

@Component({
  selector: 'app-my-matches', imports: [RouterLink, MatchCard, MatchActionSheet], changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<main class="my-page"><header><div><p>La tua agenda</p><h1>Le mie partite</h1></div><a routerLink="/partite/nuova"><i class="pi pi-plus"></i> Crea</a></header><div class="tabs" role="tablist" aria-label="Periodo"><button type="button" role="tab" [attr.aria-selected]="tab() === 'upcoming'" [class.active]="tab() === 'upcoming'" (click)="tab.set('upcoming')">Prossime</button><button type="button" role="tab" [attr.aria-selected]="tab() === 'past'" [class.active]="tab() === 'past'" (click)="tab.set('past')">Archivio</button></div>@if (store.loading() && !store.myMatches().length) { <div class="state" role="status">Caricamento agenda…</div> } @else { <section class="grid">@for (match of visibleMatches(); track match.id) { <app-match-card [match]="match" (actions)="openActions($event)" /> } @empty { <div class="state"><i class="pi pi-calendar"></i><h2>Nessuna partita</h2><p>{{ tab() === 'upcoming' ? 'Trova una partita aperta o organizzane una.' : 'Le partite concluse appariranno qui.' }}</p><a routerLink="/partite">Trova una partita</a></div> }</section>}</main><app-match-action-sheet [visible]="sheetOpen()" (visibleChange)="sheetOpen.set($event)" [match]="selectedMatch()" [userId]="auth.authUser()?.id ?? null" [busy]="store.actionMatchId() !== null" (join)="join($event)" (withdraw)="withdraw($event)" (cancel)="cancel($event)" />`,
  styles: `:host{display:block}.my-page{width:min(100%,1040px);padding:18px 16px calc(var(--bottom-nav-height) + var(--bottom-actions-height) + 48px);margin:0 auto}header{display:flex;align-items:end;justify-content:space-between;padding:24px 20px;color:white;border-radius:27px;background:linear-gradient(145deg,#071d26,#123945)}header p{margin:0 0 5px;color:#84efe3;font-size:.68rem;font-weight:900;letter-spacing:.1em;text-transform:uppercase}h1{margin:0;font:900 clamp(2rem,10vw,4rem)/.95 var(--display-font);letter-spacing:-.05em}header a{display:flex;min-height:44px;align-items:center;gap:7px;padding:0 14px;color:var(--color-ink);border-radius:14px;background:white;font-size:.76rem;font-weight:900;text-decoration:none}.tabs{display:grid;grid-template-columns:1fr 1fr;gap:5px;padding:5px;margin:14px 0;border-radius:16px;background:var(--color-surface-muted)}.tabs button{min-height:44px;border:0;border-radius:12px;color:var(--color-ink-muted);background:transparent;font-weight:850;cursor:pointer}.tabs button.active{color:var(--color-brand-strong);background:white;box-shadow:0 4px 12px rgb(7 29 38/.08)}.grid{display:grid;gap:12px}.state{display:grid;min-height:300px;place-content:center;justify-items:center;gap:9px;color:var(--color-ink-muted);text-align:center}.state i{font-size:2rem}.state h2,.state p{margin:0}.state a{min-height:44px;padding:12px 16px;color:white;border-radius:13px;background:var(--color-brand-strong);font-weight:850;text-decoration:none}button:focus-visible,a:focus-visible{outline:3px solid var(--color-focus);outline-offset:2px}@media(min-width:700px){.my-page{padding:34px 28px 120px}.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}`,
})
export class MyMatches implements OnInit, OnDestroy {
  protected readonly store=inject(MatchesStore); protected readonly auth=inject(AuthStore); private readonly actions=inject(PageActionsService); private readonly service=inject(MatchesService);
  protected readonly tab=signal<'upcoming'|'past'>('upcoming'); protected readonly selectedMatch=signal<BeachMatch|null>(null); protected readonly sheetOpen=signal(false);
  protected readonly visibleMatches=computed(()=>{const now=Date.now();return this.store.myMatches().filter(m=>this.tab()==='upcoming'?new Date(m.starts_at).getTime()>=now&&!['completed','cancelled'].includes(m.status):new Date(m.starts_at).getTime()<now||['completed','cancelled'].includes(m.status));});
  private channel?:RealtimeChannel; private timer?:ReturnType<typeof setTimeout>;
  ngOnInit():void{this.actions.set([{id:'find-match',label:'Trova partita',shortLabel:'Trova',icon:'pi-search',routerLink:'/partite'},{id:'create-match',label:'Crea partita',shortLabel:'Crea',icon:'pi-plus',primary:true,routerLink:'/partite/nuova'}]);void this.store.loadMyMatches();this.channel=this.service.subscribeToMatchChanges(()=>this.schedule());}
  ngOnDestroy():void{this.actions.clear();if(this.channel)this.service.removeChannel(this.channel);if(this.timer)clearTimeout(this.timer);}
  protected openActions(match:BeachMatch):void{this.selectedMatch.set(match);this.sheetOpen.set(true);} protected async join(id:string):Promise<void>{if(await this.store.join(id)){this.sheetOpen.set(false);await this.store.loadMyMatches(true);}} protected async withdraw(id:string):Promise<void>{if(window.confirm('Vuoi liberare il tuo posto?')&&await this.store.withdraw(id)){this.sheetOpen.set(false);await this.store.loadMyMatches(true);}} protected async cancel(id:string):Promise<void>{if(window.confirm('Annullare la partita per tutti?')&&await this.store.cancel(id)){this.sheetOpen.set(false);await this.store.loadMyMatches(true);}}
  private schedule():void{if(this.timer)clearTimeout(this.timer);this.timer=setTimeout(()=>void this.store.loadMyMatches(true),250);}
}
